version: '3'

services:
  web_gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    env_file:
      - .env.dev
    depends_on:
      - db_postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 7070:80
    depends_on:
      - web_gunicorn

  db_postgres:
    image: postgres:15
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_postgres"]
      interval: 15s
      timeout: 10s
      retries: 5


volumes:
  postgres_data:
  static_volume: